### ISSUE TITLE
PHP Process fails if no file matched

### ISSUE THREAD

**Issue by jojowork** [systopia/aip#6]
The Process.php is trying different files but does not find a match. Then the PHP-Process fails with the following error message:
`TypeError: Argument 1 passed to Civi\AIP\Finder\DropFolderFinder::claimSource() must be of the type string, null given, called in /var/www/drupal/web/sites/default/files/civicrm/ext/aip/Civi/AIP/Process.php on line 171 in Civi\AIP\Finder\DropFolderFinder->claimSource() (line 134 of /var/www/drupal/web/sites/default/files/civicrm/ext/aip/Civi/AIP/Finder/DropFolderFinder.php)`

The code Lines in Process.php:
```
170       $source_url = $this->finder->findNextSource();
171       $source_url = $this->finder->claimSource($source_url);
```
This seems to be an edge-case that is currently not covered correctly in the code

**Comment by bjendres** [comment]
Thanks for reporting.

> This seems to be an edge-case that is currently not covered correctly in the code

It's actually not that "edge" :)

**Comment by bjendres** [comment]
Was introduced with #5
