### ISSUE TITLE
create sql-tables on extension installation

### ISSUE THREAD

**Issue by jojowork** [systopia/aip#9]
Current behavior: Extension can be installed, but the necessary Data-Structure is in the SQL-Database not created.
Expected behavior: data-structure should be created on extension installation

The file [sql/auto_install.sql](https://github.com/systopia/aip/blob/fea4c97943d534720f8506d57bfa4112847fc2bd/sql/auto_install.sql#L4) should be executed as SQL during the installation of the extension.

**Comment by bjendres** [comment]
This should work with ``1.0.0```
